"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TOKEN_VALUE = exports.TOKEN_TYPE = void 0;
var TOKEN_TYPE;
(function (TOKEN_TYPE) {
    TOKEN_TYPE["START_OF_FILE"] = "START_OF_FILE";
    TOKEN_TYPE["END_OF_FILE"] = "END_OF_FILE";
    TOKEN_TYPE["TAG_OPEN"] = "TAG_OPEN";
    TOKEN_TYPE["TAG_CLOSE"] = "TAG_CLOSE";
    TOKEN_TYPE["TAG_CLOSE_SLASH"] = "TAG_CLOSE_SLASH";
    TOKEN_TYPE["ASSIGNMENT"] = "ASSIGNMENT";
    TOKEN_TYPE["AT_THE_RATE"] = "AT_THE_RATE";
    TOKEN_TYPE["INTERPOLATION"] = "INTERPOLATION";
    TOKEN_TYPE["CURLEY_BRACKET_OPEN"] = "CURLEY_BRACKET_OPEN";
    TOKEN_TYPE["CURLEY_BRACKET_CLOSE"] = "CURLEY_BRACKET_CLOSE";
    TOKEN_TYPE["STRING"] = "STRING";
    TOKEN_TYPE["SINGLE_QUOTE"] = "SINGLE_QUOTE";
    TOKEN_TYPE["DOUBLE_QUOTE"] = "DOUBLE_QUOTE";
    TOKEN_TYPE["HASH"] = "HASH";
    TOKEN_TYPE["DOLLAR"] = "DOLLAR";
    TOKEN_TYPE["PARENTHESIS_OPEN"] = "PARENTHESIS_OPEN";
    TOKEN_TYPE["PARENTHESIS_CLOSE"] = "PARENTHESIS_CLOSE";
    TOKEN_TYPE["IDENTIFIER"] = "IDENTIFIER";
    TOKEN_TYPE["FOR"] = "FOR";
    TOKEN_TYPE["SQUARE_BRACKET_OPEN"] = "SQUARE_BRACKET_OPEN";
    TOKEN_TYPE["SQUARE_BRACKET_CLOSE"] = "SQUARE_BRACKET_CLOSE";
    TOKEN_TYPE["COMMA"] = "COMMA";
    TOKEN_TYPE["COLON"] = "COLON";
    TOKEN_TYPE["SEMICOLON"] = "SEMICOLON";
    TOKEN_TYPE["IF"] = "IF";
    TOKEN_TYPE["ELSE_IF"] = "ELSE_IF";
    TOKEN_TYPE["ELSE"] = "ELSE";
    TOKEN_TYPE["SWITCH"] = "SWITCH";
    TOKEN_TYPE["CASE"] = "CASE";
    TOKEN_TYPE["TAG_NAME"] = "TAG_NAME";
    TOKEN_TYPE["ATTRIBUTE_NAME"] = "ATTRIBUTE_NAME";
    TOKEN_TYPE["ATTRIBUTE_VALUE"] = "ATTRIBUTE_VALUE";
})(TOKEN_TYPE || (exports.TOKEN_TYPE = TOKEN_TYPE = {}));
// export enum TOKEN_TYPE{
//     START_OF_FILE = 0,
//     END_OF_FILE,
//     TAG_OPEN,
//     TAG_CLOSE,
//     TAG_CLOSE_SLASH,
//     ASSIGNMENT,
//     AT_THE_RATE,
//     INTERPOLATION,
//     CURLEY_BRACKET_OPEN,
//     CURLEY_BRACKET_CLOSE,
//     STRING,
//     SINGLE_QUOTE,
//     DOUBLE_QUOTE,
//     HASH,
//     DOLLAR,
//     PARENTHESIS_OPEN,
//     PARENTHESIS_CLOSE,
//     IDENTIFIER,
//     FOR,
//     SQUARE_BRACKET_OPEN,
//     SQUARE_BRACKET_CLOSE,
//     COMMA,
//     COLON,
//     IF,
//     ELSE_IF,
//     ELSE,
//     SWITCH,
//     CASE,
//     TAG_NAME,
//     ATTRIBUTE_NAME,
//     ATTRIBUTE_VALUE,
// }
exports.TOKEN_VALUE = {
    [TOKEN_TYPE.START_OF_FILE]: "START_OF_FILE",
    [TOKEN_TYPE.END_OF_FILE]: "END_OF_FILE",
    [TOKEN_TYPE.TAG_OPEN]: "<",
    [TOKEN_TYPE.TAG_CLOSE]: ">",
    [TOKEN_TYPE.TAG_CLOSE_SLASH]: "/",
    [TOKEN_TYPE.ASSIGNMENT]: "=",
    [TOKEN_TYPE.AT_THE_RATE]: "@",
    [TOKEN_TYPE.INTERPOLATION]: 'INTERPOLATION',
    [TOKEN_TYPE.CURLEY_BRACKET_OPEN]: "{",
    [TOKEN_TYPE.CURLEY_BRACKET_CLOSE]: "}",
    [TOKEN_TYPE.STRING]: "STRING",
    [TOKEN_TYPE.SINGLE_QUOTE]: "'",
    [TOKEN_TYPE.DOUBLE_QUOTE]: '"',
    [TOKEN_TYPE.HASH]: '#',
    [TOKEN_TYPE.DOLLAR]: '$',
    [TOKEN_TYPE.PARENTHESIS_OPEN]: '(',
    [TOKEN_TYPE.PARENTHESIS_CLOSE]: ')',
    [TOKEN_TYPE.IDENTIFIER]: 'IDENTIFIER',
    [TOKEN_TYPE.FOR]: 'for',
    [TOKEN_TYPE.SQUARE_BRACKET_OPEN]: '[',
    [TOKEN_TYPE.SQUARE_BRACKET_CLOSE]: ']',
    [TOKEN_TYPE.COMMA]: ',',
    [TOKEN_TYPE.COLON]: ':',
    [TOKEN_TYPE.SEMICOLON]: ';',
    [TOKEN_TYPE.IF]: 'if',
    [TOKEN_TYPE.ELSE_IF]: 'else-if',
    [TOKEN_TYPE.ELSE]: 'else',
    [TOKEN_TYPE.SWITCH]: 'switch',
    [TOKEN_TYPE.CASE]: 'case',
    [TOKEN_TYPE.TAG_NAME]: 'TAG_NAME',
    [TOKEN_TYPE.ATTRIBUTE_NAME]: 'ATTRIBUTE_NAME',
    [TOKEN_TYPE.ATTRIBUTE_VALUE]: 'ATTRIBUTE_VALUE',
};
